---
templates:
  terraform_init_result: "#### Terraform Format and Style 🖌`${{ steps.terraform-validate.outputs.terraform-fmt-outcome }}`"

terraform:
  plan:
    template: |
      {{template "plan_title" .}}
      {{template "terraform_init_result" .}}

      {{if .Link}}[CI link]({{.Link}}){{end}}

      {{template "deletion_warning" .}}
      {{template "result" .}}
      {{template "updated_resources" .}}

      {{template "changed_result" .}}
      {{template "change_outside_terraform" .}}
      {{template "warning" .}}
      {{template "error_messages" .}}
