---
name: terraform fmt

description: Terraform Apply

inputs:
  working-directory:
    description: "Terraform CLI 実行時のパス"
    required: true

runs:
  using: composite
  steps:
    - name: Terraform Plan
      id: terraform-plan
      uses: './.github/actions/terraform-plan'
      with:
        working-directory: ${{ inputs.working-directory }}
        AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID }}
        AWS_GITHUB_ACTIONS_OIDC_ROLE: arn:aws:iam::${{ inputs.AWS_ACCOUNT_ID }}:role/oidc-github-actions

    - name: Terraform Apply
      id: terraform-apply
      run: terraform apply -auto-approve
      working-directory: ${{ inputs.working-directory }}
      shell: bash
