---
name: Setup terraform

description: Setup Terraform

inputs:
  AWS_GITHUB_ACTIONS_OIDC_ROLE:
    description: "AWS IAM Role"
    required: true
  working-directory:
    description: "Terraform CLI 実行時のパス"
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      id: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ap-northeast-1
        role-to-assume: ${{ inputs.AWS_GITHUB_ACTIONS_OIDC_ROLE }}

    - name: Get caller identity
      id: get-caller-identity
      run: aws sts get-caller-identity
      shell: bash

    - name: Get current Terraform version
      id: get-terraform-version
      run: echo "TERRAFORM_VERSION=$(cat .terraform-version)" >> $GITHUB_ENV
      shell: bash

    - name: Setup Terraform
      id: setup-terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Terraform Init
      id: terraform-init
      run: |
        terraform init
        echo "Terraform Version: ${{ env.TERRAFORM_VERSION }}"
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Sticky Pull Request Comment
      id: sticky-pull-request-comment
      uses: marocchino/sticky-pull-request-comment@v2.2.0
      with:
        hide_and_recreate: true
        header: init
        message: |
          #### Terraform Initialization ⚙️`${{ steps.init.outcome }}`
          <details><summary>Show Plan</summary>

          ```hcl

          terraform
          ${{ steps.plan.outputs.stdout }}

          ```

          </details>
