---
name: Setup terraform

description: Setup Terraform

inputs:
  AWS_ACCOUNT_ID:
    description: "AWS Account ID"
    required: true
  directory:
    description: "Terraform Working Directory"
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      id: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ap-northeast-1
        role-to-assume: arn:aws:iam::${{ inputs.AWS_ACCOUNT_ID }}:role/oidc-github-actions

    - name: Get caller identity
      id: get-caller-identity
      run: aws sts get-caller-identity
      shell: bash

    - name: Get current Terraform version
      id: get-terraform-version
      run: echo "TERRAFORM_VERSION=$(cat .terraform-version)" >> $GITHUB_ENV
      shell: bash

    - name: Setup Terraform
      id: setup-terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Terraform Init
      id: init
      working-directory: ${{ inputs.directory }}
      run: |
        terraform init
        echo "Terraform Version: ${{ env.TERRAFORM_VERSION }}"
      shell: bash
