---
name: Branch (main)

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read
  # actions: read
  pull-requests: write

env:
  ENV: dev

jobs:
  terraform:
    name: "Terraform"
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: main
            directory: main
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Terraform Plan
        id: terraform-plan
        uses: './.github/actions/terraform-plan'
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          AWS_GITHUB_ACTIONS_OIDC_ROLE: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/oidc-github-actions
          working-directory: ./${{ matrix.directory }}

      - name: Terraform Apply
        id: terraform-apply
        uses: './.github/actions/terraform-apply'
        if: github.event_name == 'push'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          AWS_GITHUB_ACTIONS_OIDC_ROLE: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/oidc-github-actions
          working-directory: ./${{ matrix.directory }}
