---
name: Branch (main)

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: "Terraform"
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: main
            directory: main
    defaults:
      run:
        working-directory: ./${{ matrix.directory }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      # - uses: './.github/actions/setup-terraform'
      #   with:
      #     AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      #     AWS_GITHUB_ACTIONS_OIDC_ROLE: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/oidc-github-actions
      #   continue-on-error: true

      # - uses: './.github/actions/terraform-validate'

      - uses: './.github/actions/terraform-plan'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_GITHUB_ACTIONS_OIDC_ROLE: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/oidc-github-actions

      - uses: './.github/actions/terraform-apply'
