---
name: Terraform Validation

description: Terraform Validation

inputs:
  working-directory:
    description: "Terraform CLI 実行時のパス"
    required: true
outputs:
  terraform-fmt-outcome:
    description: terraform fmt の処理結果
    value: ${{ steps.terraform-fmt.outcome }}
  terraform-validate-outcome:
    description: terraform validate の処理結果
    value: ${{ steps.terraform-validate.outcome }}

runs:
  using: composite
  steps:
    - name: Terraform Format
      id: terraform-fmt
      run: terraform fmt -check -recursive -diff
      shell: bash

    - name: Terraform Validate
      id: terraform-validate
      run: terraform validate -no-color
      shell: bash
