---
name: Terraform Validation

description: Terraform Validation

runs:
  using: composite
  steps:
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check -recursive -diff
      shell: bash

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      shell: bash
