---
name: Terraform Validation

description: Terraform Validation

inputs:
  working-directory:
    description: "Terraform CLI 実行時のパス"
    required: true

runs:
  using: composite
  steps:
    - name: Terraform Format
      id: terraform-fmt
      run: terraform fmt -check -recursive -diff
      shell: bash

    - name: Sticky Pull Request Comment
      id: sticky-pull-request-comment-1
      uses: marocchino/sticky-pull-request-comment@v2.2.0
      with:
        hide_and_recreate: true
        header: terraform-fmt
        message: |
          #### Terraform Format and Style `${{ steps.terraform-fmt.outcome }}`
          <details><summary>Show Plan</summary>

          ```hcl

          terraform
          ${{ steps.plan.outputs.stdout }}

          ```

          </details>

    - name: Terraform Validate
      id: terraform-validate
      run: terraform validate -no-color
      shell: bash

    - name: Sticky Pull Request Comment
      id: sticky-pull-request-comment-2
      uses: marocchino/sticky-pull-request-comment@v2.2.0
      with:
        hide_and_recreate: true
        header: terraform-validate
        message: |
          #### Terraform Validation 🤖`${{ steps.terraform-validate.outcome }}`
          <details><summary>Show Plan</summary>

          ```hcl

          terraform
          ${{ steps.plan.outputs.stdout }}

          ```

          </details>
